#!/bin/bash
crontab -l | { cat; echo "@reboot pm2 start /var/www/apphub/index.js -i 0 --name \"node-app\""; } | crontab -
sudo pm2 stop node-app
# actually start the server
sudo pm2 start /var/www/apphub/index.js -i 0 --name "node-app"
